@baseUrl = https://localhost:5001

@sellerId = d63503af-6d4f-4a6b-b242-1893d99d28e5
@bidder1 = 315dba78-1744-42d3-b824-69399448af9c
@bidder2 = 16cd09df-6063-4257-9ebb-19bb737bdd8b

@auction1 = dab1084a-3279-4c3a-84e5-96042fa71b6e

###
# Home
GET {{baseUrl}}/

###
# Create sample auction
POST {{baseUrl}}/create-sample-auction/cc44da9b-e574-4f50-bc07-09bbe5ee49ec

### 
# Create auction
POST {{baseUrl}}/create-auction/
Content-Type: application/json

{
    "AuctionId": "{{auction1}}",
    "Title": "Sample Auction",
    "Description": "A sample auction",
    "StartedBy": "{{sellerId}}",
    "StartsOn": "2023-01-31T04:27:01+00:00",
    "EndsOn": "2023-01-31T07:27:01+00:00",
    "MinimumBid": null
}

###
# Place bid
POST {{baseUrl}}/place-bid/
Content-Type: application/json

{
    "AuctionId": "{{auction1}}",
    "Bidder": "{{bidder1}}",
    "Amount": "3.20"
}

###
# Cancel auction
POST {{baseUrl}}/cancel-auction/{{auction1}}

###
# Get Auction (Projection)
GET {{baseUrl}}/get-auction/{{auction1}}
